### ISSUE TITLE
Not able to verify Gobra files in Nightly version

### ISSUE THREAD

**Issue by Timon555** [viperproject/gobra-ide#206]
After changing the build version from Stable to Nightly and restarting the IDE, the Gobra files are no longer being verified. 
The error message is: 'gobra.verifyFile' not found.

**Comment by ArquintL** [comment]
Thanks for the report! There was a CI issue while creating the nightly release resulting in an incomplete release. This should be fixed now. Could you please try to execute the "Update Gobra Tools" command?

**Comment by Timon555** [comment]
It works, thank you!
